#!/bin/bash

BASEURL="http://inventory.hackf.org/doku.php?id="
TEMPPNG=".hfinvtag-qr-tmp.png"

IMAGES=("hfinv_123x250.png")
QROPTS=("-s 3 -m 4")
GEOMETRY=("+0+86")

show_help()
{
    echo "Usage: $0 [-i id | -r number] -s size"
    echo
    echo "Possible sizes are:"
    size=0
    for psize in ${IMAGES[*]}; do
        echo -en "\t$size\t"
        identify images/$psize | cut -f3 -d' '
        size=$(( $size + 1 ))
    done
}

random=0
ids=()

while getopts "hi:r:s:" opt; do
    case "$opt" in
    h)  show_help
        exit 0
        ;;
    i)  ids[0]=$OPTARG
        ;;
    r)  random=$OPTARG
        ;;
    s)  size=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

if (( $random > 0 )); then
    ids=($(python generate_random_id.py 20 $random))
fi

if [[ ! "${ids[0]}" ]] || [[ ! "$size" ]] || [[ ! "${IMAGES[$size]}" ]]; then
    show_help
    exit 1
fi

for id in ${ids[*]}; do
    qrencode ${QROPTS[$size]} -t PNG -o $TEMPPNG $BASEURL$id
    composite -geometry ${GEOMETRY[$size]} $TEMPPNG images/${IMAGES[$size]} $id.png
    rm -f $TEMPPNG
done
